services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - common-network

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    environment:
      - ETCD_NAME=etcd-server
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd-server=http://0.0.0.0:2380
    networks:
      - common-network

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    ports:
      - "4222:4222"   # NATS server client connections
      - "8222:8222"   # NATS server monitoring
      - "6222:6222"   # NATS server routing connections (cluster port)
      - "8223:8223"   # NATS Streaming server monitoring
    environment:
      - "STAN_CLUSTER_ID=test-cluster"
      - CLUSTER_ID=test-cluster      # NATS Streaming cluster ID
      - STORE=file                   # Storage type (file or memory)
      - DIR=/data/nats-streaming     # Directory for file storage
    command: [
      "-p", "4222",
      "-m", "8222"
    ]
    volumes:
      - nats_streaming_data:/data/nats-streaming  # Volume for persistence # - "./nats-streaming-1:/data"

    networks:
      - common-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - common-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bi_main
      MYSQL_USER: apple
      MYSQL_PASSWORD: 123456
    volumes:
      # - mysql_data:/var/lib/mysql
      - /Users/yinyong/GitRepos/docker-common-components/data/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - common-network

volumes:
  mysql_data:
  mongodb_data:
  etcd_data:
  nats_data:
  nats_streaming_data:
  
networks:
  common-network:
