services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - common-network

  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    environment:
      - ETCD_NAME=etcd-server
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=etcd-server=http://0.0.0.0:2380
    networks:
      - common-network

  nats:
    image: nats:2.1.8-alpine3.11
    container_name: nats

    networks:
      - common-network
    command: 
      - "--debug"
      - "--cluster"
      - "nats://nats:6222"
      - "--http_port"
      - "8222"
      - "--port" 
      - "4222"
    ports: 
      - "4222:4222"
      - "18222:8222"

  nats-streaming:
    image: nats-streaming:0.18.0-alpine
    container_name: nats-streaming
    networks:
      - common-network
    command: 
      - "--clustered"
      - "--nats_server"
      - "nats://nats:6222"
      - "--cluster_bootstrap"
      - "--cluster_node_id"
      - "node1"
      - "--cluster_log_path"
      - "/data/log"
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - "/data/msg"
      - "--store"
      - "file"
      - "--cluster"
      - "nats://nats:6222"
      - "--stan_debug"
      - "--http_port"
      - "8222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    ports: 
      - "18224:8222"
    volumes:
      - "./nats-streaming-1:/data"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    networks:
      - common-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bi_main
      MYSQL_USER: apple
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - common-network

volumes:
  mysql_data:
  mongodb_data:
  etcd_data:
  nats_data:
  
networks:
  common-network:
